random_seed: 9999
debug: False
# use_wandb: False
device: cuda
device_id: 1

train:
  use_tensorboard: True
  log_dir: 'log'
  checkpoints_dir: "checkpoints"
  group: 'debug'
  save_name: 'debug'
  learning_rate: 1.e-4
  optimizer: 'AdamW'
  batch_size: 64
  loss: 'MSE'
  max_epoch: 50
  use_checkpoint_asinit: False
  checkpoint_id: 25
  

test:
  test: False
  batch_size: 1

model:
  model_root: ../pretrain_model
  model_type: vit_h
  load_decoder: True
  decoder_path: ../finetune_model/box_8605.pth
  load_classifier: False
  classifier_path: ../finetune_model/0.4_1x512x512_epoch49.pth
  classifier_type: cnn

data:
  data_root: "../BTCV_dataset1"
  promt_type: "box"
  split_ratio: 0.2
  img_size: [512, 512]
  input_size: [1024, 1024]
  use_embedded: False
  data_name: vit-h_embedding_bc1
  info_name: pre_processed_dataset1
  load_from_disk: False

     
promt:
  promt_type: "box"
  center_point: False
  point_num: 16
  point_size: 16