random_seed: 9999
debug: False
# use_wandb: False
device: cuda
device_id: 1

train:
  use_tensorboard: True
  log_dir: 'log'
  group: 'debug'
  save_name: 'debug'
  learning_rate: 1.e-6
  optimizer: 'AdamW'
  batch_size: 8
  loss: 'MSE'
  max_epoch: 50
  use_checkpoint_asinit: True
  checkpoint_id: 25
  

test:
  test: False
  batch_size: 1

model:
  model_root: ../pretrain_model
  model_type: vit_h


data:
  data_root: "../BTCV_dataset1"
  promt_type: "box"
  split_ratio: 0.2
  img_size: [512, 512]
  input_size: [1024, 1024]
  use_embedded: False
  data_name: pre_processed_dataset1
  info_name: pre_processed_dataset1
  load_from_disk: False

     
