random_seed: 9999
debug: False
# use_wandb: False
device: cuda
device_id: 1

train:
  use_tensorboard: True
  log_dir: 'log'
  checkpoints_dir: "checkpoints"
  group: 'debug'
  save_name: 'debug'
  learning_rate: 5.e-5
  warmup_iter: 150
  optimizer: 'AdamW'
  weight_decay: 1.e-3
  batch_size: 8
  loss: 'MSE'
  max_epoch: 50
  use_checkpoint_asinit: True
  checkpoint_id: 49
  

test:
  test: False
  batch_size: 1

model:
  model_root: ../pretrain_model
  model_type: vit_h
  load_decoder: False
  classifier_root: ../pretrain_model
  classifier_type: cnn

data:
  data_root: "../BTCV_dataset1"
  promt_type: "box"
  split_ratio: 0.2
  img_size: [512, 512]
  input_size: [1024, 1024]
  use_embedded: True
  data_name: pre_processed_dataset1
  info_name: pre_processed_dataset1
  load_from_disk: False

     
