random_seed: 9999
debug: False
# use_wandb: False
device: cuda
device_id: 1

train:
  use_tensorboard: True
  log_dir: '/home/xuyichen/data/ML_project/Task3/log_together/points_centered'
  checkpoints_dir: "checkpoints/points"
  group: 'debug'
  save_name: 'debug'
  learning_rate: 1.e-4
  linear_warmup: False
  warmup_iter: 150
  optimizer: 'AdamW'
  weight_decay: 1.e-3
  batch_size: 16
  loss: 'MSE'
  max_epoch: 100
  use_checkpoint_asinit: False
  checkpoint_id: 46
  lambda_classifier: 3
  merge_type: 
  

test:
  test: True
  batch_size: 1

model:
  model_root: ../pretrain_model
  model_type: vit_h
  load_decoder: True
  decoder_path: ../finetune_model/points_center_7860.pth
  load_classifier: True
  classifier_path: ../finetune_model/pointscenter2.pth
  classifier_type: cnn

data:
  data_root: "../BTCV_dataset1"
  promt_type: “points"
  split_ratio: 0.2
  img_size: [512, 512]
  input_size: [1024, 1024]
  use_embedded: True
  data_name: vit-h_embedding_bc1
  info_name: pre_processed_dataset1
  load_from_disk: False

     
promt:
  promt_type: "points"
  center_point: True
  point_num: 16
  point_size: 16